Feature/cop 7878 save and continue action
UKHomeOffice/workflow-service pull request #119
Opened 2022-01-19 16:45 UTC by hiteshprayosha

- Enable Save and Continue 
- Draft Data will be saved in S3 bucket
- Draft Data will be not saved in Elastic Search
- Added **saveForm** flag for Form (Draft Form)

2022-01-20 13:43 UTC, michaelruocco commented on src/main/java/io/digital/patterns/workflow/aws/AwsProperties.java
> +    private String dataBucketName;
would a better name for this potentially be savedFormsBucket?

2022-01-20 13:48 UTC, michaelruocco commented on src/main/java/io/digital/patterns/workflow/data/FormDataService.java
> +            if(request.getForm().isSaveForm()) {
you are reaching into the form to get is saveForm twice here, it might be better to add a method to the request object and call it just once. Also, I am not sure when tryPerformUpload was made public, but now that it has been made public it should probably be renamed, as this code looks a bit odd with the way to two methods inside the if statement read, it would be better if the methods were renamed (admittedly I named them in the first place! but whilst one was private they didn't seem so bad) i.e.

```
boolean saveForm = request.isSaveForm();
log.info("Save and continue form {}", saveForm);
if (saveForm) {
    uploaded = s3Uploader.upload(key, request.getBucketName(), metadata, form);
} else {
    uploaded = s3Uploader.uploadIfDoesNotExist(key, request.getBucketName(), metadata, form);
}
```

2022-01-20 13:49 UTC, michaelruocco commented on src/main/java/io/digital/patterns/workflow/data/FormDataVariablePersistListener.java
> +            log.info("afterCompletion status = " + String.valueOf(status));
do you need all these logs or can they be removed? if they are needed, rather than appending you should use the logging placeholder. i.e.

```
log.info("afterCompletion status = {} ", status);
```

2022-01-20 13:50 UTC, michaelruocco commented on src/main/java/io/digital/patterns/workflow/data/FormDataVariablePersistListener.java
> +                // log.info("formJson => " + formJson);
commented out line should be removed.

2022-01-20 13:53 UTC, michaelruocco commented on src/main/java/io/digital/patterns/workflow/data/FormDataVariablePersistListener.java
> +                }
the product variable is passed into this save method, if you want to change the way it is built up, you should do it inside the resolve product name method rather than overwriting it inside the save as it is confusing to a method caller to overwrite the name that is passed in in some scenarios.

2022-01-20 13:54 UTC, michaelruocco commented on src/main/java/io/digital/patterns/workflow/encrypt/VariableEncryptInterceptor.java
> +        log.info("process-instance and path " + requestContext.getUriInfo().getPath());
do you need to log both the uri info and the path as well here? Also same as above, if you keep these logs, you should use the logging placeholder rather than appending, i.e.

```
log.info("process-instance and UriInfo {} ", requestContext.getUriInfo());
```

2022-01-20 13:54 UTC, michaelruocco commented on src/main/resources/application.yml
> +  data-bucket-name: ${aws.s3.data-bucket-name}
as before, would this be better named something live saved-forms-bucket-name?

2022-01-20 13:54 UTC, michaelruocco commented on src/test/groovy/io/digital/patterns/workflow/data/FormDataServiceSpec.groovy
> +            .disableExplicitESave(false);
why was this added?

2022-01-20 13:56 UTC, michaelruocco commented on src/test/groovy/io/digital/patterns/workflow/data/FormDataServiceSpec.groovy
> +                   "saveForm": true
I notice the method mentions draft mode, rather than calling the json variable saveForm, would it be better to be named draft?

i.e.

```
"draft": true
```

2022-01-20 13:57 UTC, michaelruocco commented on src/main/java/io/digital/patterns/workflow/common/Form.java
> +    private final boolean saveForm;
from reading the test below, would it be better to have this variable named draft, rather than save form? I think it makes it clearer that the form is a draft form, rather than saying the form is a saveForm form.

2022-01-20 14:16 UTC, michaelruocco requested changes
Generally the change looks good, I have suggested a few naming improvements (at least in my opinion!) and it might be worth taking out some of the logging or turning it down to debug level too.

2022-01-20 17:26 UTC, hiteshprayosha commented on src/main/java/io/digital/patterns/workflow/aws/AwsProperties.java
> +    private String dataBucketName;
applied as draftBucketName

2022-01-20 17:26 UTC, hiteshprayosha commented on src/main/java/io/digital/patterns/workflow/data/FormDataService.java
> +            if(request.getForm().isSaveForm()) {
👍

2022-01-20 17:27 UTC, hiteshprayosha commented on src/main/java/io/digital/patterns/workflow/data/FormDataVariablePersistListener.java
> +                }
yes, I have planned and now moved to resolveProductName()

2022-01-20 17:32 UTC, hiteshprayosha commented on src/main/resources/application.yml
> +  data-bucket-name: ${aws.s3.data-bucket-name}
draft-bucket-name: ukbf-dev-cop-data

2022-01-20 17:34 UTC, hiteshprayosha commented on src/test/groovy/io/digital/patterns/workflow/data/FormDataServiceSpec.groovy
> +                   "saveForm": true
draftForm, which is more real and make sense.

2022-01-21 16:44 UTC, michaelruocco approved these changes
LGTM thanks for making those changes, much appreciated.

2022-01-24 15:42 UTC, michaelruocco commented
@hiteshprayosha are you okay to merge this now or are you still waiting for other changes / approvals?

2022-01-25 10:20 UTC, merged